CREATE TABLE [stg_fact].[QA_ServiceQuality_PassengerSurvey] (
    [DateKey]                  INT            NULL,
    [TimeKey]                  INT            NULL,
    [AgeKey]                   INT            NULL,
    [GenderKey]                INT            NULL,
    [DefaultTransportModeKey]  INT            NULL,
    [LineKey]                  INT            NULL,
    [TimeSpanKey]              INT            NULL,
    [ContractorKey]            INT            NULL,
    [OperatingDayTypeKey]      INT            NULL,
    [PurposeKey]               NVARCHAR (255) NULL,
    [FrequencyKey]             NVARCHAR (255) NULL,
    [PlacementKey]             NVARCHAR (255) NULL,
    [LanguageKey]              NVARCHAR (255) NULL,
    [FromStopPointNumberKey]   INT            NULL,
    [SurveyQuestionKey]        INT            NULL,
    [SurveyAnswerKey]          INT            NULL,
    [InterviewTypeKey]         INT            NULL,
    [DataQualityTypeKey]       INT            NULL,
    [JourneyRef]               NCHAR (18)     NULL,
    [FileId]                   INT            NULL,
    [SourceSystemCode]         NVARCHAR (20)  NULL,
    [SourceSystemEntryId]      NVARCHAR (255) NULL,
    [InterviewId]              NVARCHAR (255) NULL,
    [InterviewerId]            NVARCHAR (255) NULL,
    [InterviewerStartStopNo]   INT            NULL,
    [InterviewerEndStopNo]     INT            NULL,
    [RespondentId]             NVARCHAR (255) NULL,
    [AnswerValue]              NVARCHAR (255) NULL,
    [InterviewStartLatitude]   DECIMAL (8, 6) NULL,
    [InterviewStartLongitude]  DECIMAL (8, 6) NULL,
    [DatedVehicleJourneyId]    DECIMAL (16)   NULL,
    [SourceSystemEntryRef]     NVARCHAR (100) NULL,
    [Line]                     NVARCHAR (255) NULL,
    [ContractorName]           NVARCHAR (255) NULL,
    [BusNo]                    NVARCHAR (255) NULL,
    [PurposeValue]             NVARCHAR (255) NULL,
    [TimeSpanTotalMinutes]     NVARCHAR (255) NULL,
    [FrequencyValue]           NVARCHAR (255) NULL,
    [GenderNumber]             NVARCHAR (255) NULL,
    [AgeYears]                 NVARCHAR (255) NULL,
    [PlacementValue]           NVARCHAR (255) NULL,
    [LanguageValue]            NVARCHAR (255) NULL,
    [FromStopPointNumber]      NVARCHAR (255) NULL,
    [datetime2]                DATETIME2 (7)  NULL,
    [ContractorCode]           NVARCHAR (20)  NULL,
    [DefaultTransportModeCode] NVARCHAR (20)  NULL,
    [LineNumber]               INT            NULL,
    [OperatingDayType]         INT            NULL
);


GO

